### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [mattstone22133/Learning-OpenGL-CoreProfile#1]
Hello, under what license is this project released under ? I would like to study it to learn more about OpenGL. Thank you.

**Comment by matts-dev** [comment]
Hey suprafun, that is actually a complicated question to answer. There's a couple reasons.

First, this is my place where I just implement all of the tutorials I have followed over the internet. So a lot of the art assets are not mine (3d models specifically). So I have been reluctant to add a license because I would have to go through each of those sources and dig up the rights for those assets; which isn't something I currently have time or desire to do. All of them should be shareable, but I don't want to be on the hook for figuring our their licenses again.

Another issue is that I have prototypes for games in this repository, and I wouldn't want someone to just copy the prototype and release it as their own. 

Last issue is the libraries (eg Assimp, imgui, nhlonman::json) I have used potentially all have different licenses.

As for the OpenGL sample code, I don't have a problem with anyone using or modifying it; I'm not going to track anyone down for using this code, but at this point in time I do not want to take any stance on a license, mostly to protect myself. Obviously no warranty and I'm not responsible for liabilities. 

I'm not planning on accepting pull requests for this repository. Most of that this my own code, and the code that isn't mine is documented at the top of the file from where I got it from and can be traced back that way. Most tutorials followed were https://learnopengl.com/ and http://ogldev.atspace.co.uk/ but there were others sprinkled in there too.

Hope that helps? I realize it isn't ideal. :\ Though most of the code is pretty straightforward and just a demonstration of OpenGL, so shouldn't be too much work to just read it and make your own version. :)

**Comment by suprafun** [comment]
Thank-you so very much to explaining everything so clearly. I appreciate how its hard to keep a track of things. I think I will continue my learning from more basic tutorials. Thank-you again for taking the effort to carefully explain things to me.
